### ISSUE TITLE
Mentor login, no map displayed

### ISSUE THREAD

**Issue by jetengr** [MrFlark/mentormaps#95]
when i login as mentor, no map is displayed.  There are many other issues that we need to discuss before rolling out.  Please consider talking with me this weekend so I can demonstrate.  I'm sorry, I don't have the time to capture them all in the reports.  It's critical that these issues are resolved as users will quickly make their assessment of the site and word will not spread if there are moderate issues.  thx, Evan Smith

**Comment by itsjustjon** [comment]
The map might not  be displayed because a valid address was not entered. Other than that, I do not know what is causing that.

If you can, please provide more detail so Joey and I can research your issue.

Thanks Mr. Smith,
Jon

**Comment by MrFlark** [comment]
The most likely cause of this issue is an unsuccessful geocode on google's part.
Basically, with the address you gave Google Maps, it was unable to return a latitude, longitude, or both.
To fix this please try logging in and heading to http://mentormaps.net/edit.php and reenter your address to submit another geocode request.

thanks,
Joey

**Comment by jetengr** [comment]
I did try to leave off the address value, so you are correct about the location missing.  I tried editing my profile to add the address, but no change.  I also deleted my profile and created a new one with an address.  I validated the profile from my email (which, by the way directs you to the change password, don't understand why).  After logging on, the map still does not show up.  thx

**Comment by itsjustjon** [comment]
We just pushed an update that should have resolved the change password redirect issue, so I would suggest trying again now.

For now, it might be best to fill out the full address only because leaving it out seems to cause more issues on our end that do not seem resolvable. We will look into it over today and tomorrow.

Sorry for any inconvenience,
Jon

**Comment by jetengr** [comment]
I tried using a different PC and browser.  Previously, I was using my work laptop that has Firefox ESR 31.8.0.  I tried on Chrome on a home laptop and the map works there.  do you want me to continue posting issues or do you want me to send them via email?

**Comment by itsjustjon** [comment]
An email would be good since it is easier for you to mark something as a Suggestion or Essential or Bug. Would you be fine with that?
